# Generated by Django 5.2 on 2025-04-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('char_id', models.AutoField(db_column='termId', primary_key=True, serialize=False)),
                ('character', models.TextField()),
                ('pinyin', models.TextField()),
                ('tone', models.TextField()),
                ('translation', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Characters',
            },
        ),
    ]
