# Generated by Django 5.2 on 2025-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='char_id',
            field=models.AutoField(db_column='char_id', primary_key=True, serialize=False),
        ),
    ]
