# Generated by Django 5.2 on 2025-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_characters_char_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'ordering': ['active', 'right_cnt']},
        ),
        migrations.AddField(
            model_name='characters',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='in_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='characters',
            name='right_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
