# Generated by Django 5.2 on 2025-04-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_characters_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'ordering': ['-active']},
        ),
    ]
